PV-27 missing method
jpbsheppard/AmidoTestApp pull request #5
Opened 2017-06-01 22:53 UTC by jpbsheppard

Added method for this bug and updated test with new endpoint and test passes

2017-06-02 11:08 UTC, fc572 requested changes

2017-06-02 11:08 UTC, fc572 commented on amido-test-app.iml
>        <configuration />
This file needs not to be commited

2017-06-02 11:08 UTC, fc572 commented on amido-test-app.iml
>        <configuration />
Also in your IDEA, set the language level to java 8

2017-06-05 08:20 UTC, jpbsheppard commented
Going to create a new request as git has got itself in a twist

2017-06-05 08:20 UTC, closed without merging